### ISSUE TITLE
Can't edit jumplinks - ID is 0 - There will always be new Jumplink created

### ISSUE THREAD

**Issue by FlipZoomMedia** [rockettpw/jumplinks#11]
Recently, a strange bug has appeared. If I want to edit a Jumplink, the form to create a new jumplink is always displayed. I can not edit existing entries. Here's a video:

![20160704_124906](https://cloud.githubusercontent.com/assets/708183/16558425/f3d598f2-41e5-11e6-8fd2-5dc231a7db31.gif)

I was able to locate the problem, it is the PHP isset() check in line [L1161](https://github.com/rockettpw/jumplinks/blob/master/ProcessJumplinks.module.php#L1161). The interrogation of the value is no check whether a variable is set. If you first initialize the variable with the value, it works.

**So, to fix it, change the following in line 1161:** 
```php
// Get the ID if we're editing
$editingId = $this->input->get->id;
$editingId = (isset($editingId) AND $editingId > 0 AND is_numeric($editingId)) ? $editingId : 0;
```

**Same in line [L1523](https://github.com/rockettpw/jumplinks/blob/master/ProcessJumplinks.module.php#L1523).**

ProcessWire Version 3.0.16+
PHP Version: 7.0.7
Jumplink Version: 1.5.2

**Comment by mikerockett** [comment]
Thanks David, much appreciated. I've committed the change to dev, please would you confirm that it is working? (Note that I made the commits from another PC as my main drive is giving my headaches this week, so I can't test on my local PHP7.)

**Comment by mikerockett** [comment]
@FlipZoomMedia - Have you had a chance to test?

**Comment by FlipZoomMedia** [comment]
Excuse me, I'm in the middle of moving. But yes, the fix work. :) But I have again looked through the code and I would also adjust the line in [1204](https://github.com/rockettpw/jumplinks/blob/master/ProcessJumplinks.module.php#L1204).

```php
if ($editingId == 0 && $this->input->get->source != "") {
    $sourcePath = urldecode($this->input->get->source);
}
```

**Comment by mikerockett** [comment]
No worries - hope it's going well.
Have committed to dev, as above. Will do some of my own testing soon, and then I'll push to master 1.5.3
