### ISSUE TITLE
Feature request: export jumplinks

### ISSUE THREAD

**Issue by FlipZoomMedia** [rockettpw/jumplinks#12]
It would be nice if to the import function exists also an export function to easily migrate between two installations.

**Comment by mikerockett** [comment]
Thanks David, this is on the to-do list for v2. :+1:

**Comment by FlipZoomMedia** [comment]
Very good :)

**Comment by mikerockett** [comment]
Closing this issue as it is mentioned in the roadmap and I would like the 2.0.0 milestone to be a little more accurate (this duplicates the point by remaining open).
