### ISSUE TITLE
Support Cyrillic Alphabet in Links

### ISSUE THREAD

**Issue by TomasKostadinov** [rockettpw/jumplinks#13]
Links with cyrillic symbols (eg. естетична-стоматология.html) always return 404. This is a problem for moving Bulgarian/Russian/... sites to ProcessWire with this plugin.

If you convert them so they look like this: 
%D0%BD%D
%D0%BD%D0%BE%D0%B2%D0%B8%D0%BD%D0%B8.html with php's `urlencode()` it will work.

**Comment by mikerockett** [comment]
I'll try my best to take care of this for 2.0. Development on that front is trickling in due to current commitments.

Please feel free to submit a PR for the current dev branch - I'd like to move that to stable soon.

Thanks :+1:

**Comment by TomasKostadinov** [comment]
I'll try to fix it. Changing line 1400 from 

`$source = ltrim($this->db->escape_string($input->sourcePath), '/');`

to

`$source = ltrim($this->db->escape_string(urlencode($input->sourcePath)), '/');`
seems to fix it, but now it's even converting `/` to `%2F`

**Comment by mikerockett** [comment]
That line is on the current master branch, but the dev branch has this on [line #1397](/rockettpw/jumplinks/blob/dev/ProcessJumplinks.module.php#L1397):

```php
$source = ltrim($input->sourcePath, '/');
```

Would you be able to try it out with the dev branch and let me know what happens?

**Comment by TomasKostadinov** [comment]
@mikerockett I fixed it for my customers with the current version on the master branch.
I'll fork your dev branch and try out to fix it now.

**Comment by mikerockett** [comment]
I'm busy working on Jumplinks 2, which now has full support for UTF8 URIs. These are saved correctly in the database (using `utf8_unicode_ci` collation), and I have tested your example above to check that it does indeed work.

However, in order for these to work properly, you will need to edit your `.htaccess` file to allow UTF8 characters. It's as simple as commenting out the rule for 16a and uncommenting the rule for 16b, resulting in:

```apache
  # PW-PAGENAME
  # -----------------------------------------------------------------------------------------------
  # 16a. Ensure that the URL follows the name-format specification required by PW
  # See also directive 16b below, you should choose and use either 16a or 16b.
  # -----------------------------------------------------------------------------------------------

  # RewriteCond %{REQUEST_URI} "^/~?[-_.a-zA-Z0-9/]*$"

  # -----------------------------------------------------------------------------------------------
  # 16b. Alternative name-format specification for UTF8 page name support.
  # If used, comment out section 16a above and uncomment the directive below. If you have updated
  # your $config->pageNameWhitelist make the characters below consistent with that.
  # -----------------------------------------------------------------------------------------------

  RewriteCond %{REQUEST_URI} "^/~?[-_./a-zA-Z0-9æåäßöüđжхцчшщюяàáâèéëêěìíïîõòóôøùúûůñçčćďĺľńňŕřšťýžабвгдеёзийклмнопрстуфыэęąśłżź]*$"
```

Going to label this as fixed for now, until I have some confirmation from others when I upload an alpha.

**Comment by mikerockett** [comment]
Here's a debug log to show that it works:

```
Jumplinks Match Event: Array
(
    [Version ID] => 2.8.28/2.0.0
    [Request] => /естетична-стоматология.html
    [Timestamp] => Tue, 09 Aug 2016 10:23:47 +0200 Africa/Johannesburg
)
Matched Jumplink Object: Array
(
    [modelAttributes] => Array
        (
            [id] => 4
            [created_at] => 2016-08-08 18:48:09
            [updated_at] => 2016-08-08 18:48:09
            [user_created] => 1
            [user_updated] => 1
            [from] => естетична-стоматология.html
            [to] => стоматология.html
            [enabled] => 1
            [force_temp] => 0
            [deep_clean] => 0
            [start] => 
            [end] => 
        )

    [fromLog] => Array
        (
            [original] => естетична-стоматология.html
        )

)
Compiled Destination: http://jumplinks-two.local/стоматология.html
No start/end times defined - will redirect when debug mode is deactivated.
```

**Comment by mikerockett** [comment]
And just a quick note about this: I don't intend on adding built-in parameter support for UTF8 characters is this is often not used. That said, it will be easy to include your own characters by specifying an expression for the parameter: `{name:[\w\pL]+}`

I haven't actually tested this as yet as I'm moving my initial test phase code into the module itself; so I'll tackle this aftewards, if it's necessary. Off the top of my head, I can imagine that I would only need to apply a unicode flag to FastRoute's expression holders.

**Comment by TomasKostadinov** [comment]
@mikerockett Thank you for your hard work in this plugin. 
If I understood you correctly, the only thing I need to change is the .htaccess file am I right?

PS: This is Aesthetic S**`tomato`**logy in english :laughing: .

**Comment by mikerockett** [comment]
@TomasKostadinov - You're most welcome. Hoping this will be a solid release and that users will enjoy the new features. Code will be pushed to a new `dev` as soon as it is ready. Right now, much of the module is incomplete. You can see the current todo over at #14.

Hehe, that is pretty cool. :laughing:

**Comment by mikerockett** [comment]
Closing this issue as it is complete on my end and would like to progress the 2.0.0 milestone for a more accurate progress-report.
