### ISSUE TITLE
there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

### ISSUE THREAD

**Issue by neildaemond** [rockettpw/jumplinks#18]
(affects PHP < 5.6)

caused by https://github.com/rockettpw/jumplinks/commit/cc4281aa1a4545fe1e8206a545d0b2088cc50759

**Comment by mikerockett** [comment]
Hi, and thanks for opening this. I have tackled this issue before, and somewhere along the line it created an issue for some folks (can't remember the details right now). I will look into this a little further, but would prefer to leave it as is giving consideration to Jumplinks 2 development (I've switched over to Illuminate Database).

**Comment by mikerockett** [comment]
As this exception relates to older versions of MySQL, I will not be fixing this issue. I recommend that you upgrade to MySQL 5.7.
